// data.jsx — Movies, friends, recommendations, lists
// Mock data using real well-known titles per user choice.

const FRIENDS = [
  { id: 'sof', name: 'Sofía Restrepo',  hue: 18,  initial: 'S', relation: 'Hermana' },
  { id: 'mat', name: 'Mateo Vélez',     hue: 200, initial: 'M', relation: 'Mejor amigo' },
  { id: 'ana', name: 'Ana Lucía',       hue: 320, initial: 'A', relation: 'Amiga' },
  { id: 'jul', name: 'Julián Pardo',    hue: 145, initial: 'J', relation: 'Primo' },
  { id: 'val', name: 'Valeria Ortiz',   hue: 50,  initial: 'V', relation: 'Amiga' },
  { id: 'dan', name: 'Daniel Castaño',  hue: 270, initial: 'D', relation: 'Hermano' },
  { id: 'isa', name: 'Isabela Ríos',    hue: 10,  initial: 'I', relation: 'Mamá' },
  { id: 'nic', name: 'Nicolás Hoyos',   hue: 165, initial: 'N', relation: 'Amigo' },
  { id: 'cam', name: 'Camila Henao',    hue: 290, initial: 'C', relation: 'Prima' },
];

// Posters use layered gradients + a typographic title — visually rich without
// any external image dependencies.
const MOVIES = [
  {
    id: 'kings-speech',
    title: 'El discurso del rey',
    enTitle: "The King's Speech",
    year: 2010,
    runtime: '1h 58m',
    genres: ['Drama', 'Histórica', 'Biografía'],
    rating: 'TP',
    synopsis: 'Tras la abdicación de su hermano, el príncipe Alberto, quien sufre de tartamudez, debe asumir el trono. Con la ayuda de un terapeuta del lenguaje poco ortodoxo, el rey Jorge VI debe encontrar su voz para liderar a Inglaterra a través de la guerra.',
    cast: ['Colin Firth', 'Geoffrey Rush', 'Helena Bonham Carter'],
    director: 'Tom Hooper',
    palette: ['#3a2c1e', '#a87543', '#e8c489'],
    accent: '#e8c489',
    kind: 'movie',
  },
  {
    id: 'parasite',
    title: 'Parásitos',
    enTitle: 'Parasite',
    year: 2019,
    runtime: '2h 12m',
    genres: ['Thriller', 'Drama', 'Suspenso'],
    rating: '+15',
    synopsis: 'La codicia y la discriminación de clase amenazan la nueva relación simbiótica entre la rica familia Park y el clan empobrecido Kim.',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
    director: 'Bong Joon-ho',
    palette: ['#1a1612', '#6b4226', '#c9a961'],
    accent: '#c9a961',
    kind: 'movie',
  },
  {
    id: 'spirited',
    title: 'El viaje de Chihiro',
    enTitle: 'Spirited Away',
    year: 2001,
    runtime: '2h 5m',
    genres: ['Animación', 'Fantasía', 'Familiar'],
    rating: 'TP',
    synopsis: 'Una niña de diez años entra en un mundo gobernado por dioses y brujas, donde los humanos son convertidos en bestias.',
    cast: ['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki'],
    director: 'Hayao Miyazaki',
    palette: ['#2c4a5a', '#d97a3a', '#f4e4bc'],
    accent: '#f4a23a',
    kind: 'movie',
  },
  {
    id: 'amelie',
    title: 'Amélie',
    enTitle: 'Le Fabuleux Destin d\u2019Amélie Poulain',
    year: 2001,
    runtime: '2h 2m',
    genres: ['Romance', 'Comedia'],
    rating: '+13',
    synopsis: 'Amélie es una joven introvertida que decide cambiar la vida de quienes la rodean para mejor, mientras lucha con su propio aislamiento.',
    cast: ['Audrey Tautou', 'Mathieu Kassovitz'],
    director: 'Jean-Pierre Jeunet',
    palette: ['#5a2a1f', '#d4534a', '#f0c674'],
    accent: '#e85a4f',
    kind: 'movie',
  },
  {
    id: 'past-lives',
    title: 'Vidas pasadas',
    enTitle: 'Past Lives',
    year: 2023,
    runtime: '1h 45m',
    genres: ['Romance', 'Drama'],
    rating: '+13',
    synopsis: 'Dos amigos de la infancia se reencuentran en Nueva York para una semana fatídica que los hace confrontar el destino y el amor.',
    cast: ['Greta Lee', 'Teo Yoo', 'John Magaro'],
    director: 'Celine Song',
    palette: ['#1f2e3d', '#4a6b8a', '#e8b896'],
    accent: '#e8b896',
    kind: 'movie',
  },
  {
    id: 'roma',
    title: 'Roma',
    enTitle: 'Roma',
    year: 2018,
    runtime: '2h 15m',
    genres: ['Drama', 'Histórica'],
    rating: '+15',
    synopsis: 'Una historia íntima y épica sobre Cleo, una empleada doméstica de una familia de clase media en la Ciudad de México de los años 70.',
    cast: ['Yalitza Aparicio', 'Marina de Tavira'],
    director: 'Alfonso Cuarón',
    palette: ['#2a2a2a', '#5e5e5e', '#c4c4c4'],
    accent: '#c4c4c4',
    kind: 'movie',
  },
  {
    id: 'oppenheimer',
    title: 'Oppenheimer',
    enTitle: 'Oppenheimer',
    year: 2023,
    runtime: '3h 0m',
    genres: ['Drama', 'Histórica', 'Biografía'],
    rating: '+15',
    synopsis: 'La historia del físico estadounidense J. Robert Oppenheimer y su papel en el desarrollo de la bomba atómica.',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Robert Downey Jr.'],
    director: 'Christopher Nolan',
    palette: ['#1a0f08', '#7a3a1a', '#e85d2a'],
    accent: '#e85d2a',
    kind: 'movie',
  },
  {
    id: 'casa-papel',
    title: 'La casa de papel',
    enTitle: 'Money Heist',
    year: 2017,
    runtime: '5 temporadas',
    genres: ['Acción', 'Thriller', 'Crimen'],
    rating: '+15',
    synopsis: 'Un misterioso hombre conocido como El Profesor recluta a una banda de ocho personas con habilidades únicas para llevar a cabo el atraco más ambicioso de la historia.',
    cast: ['Úrsula Corberó', 'Álvaro Morte', 'Itziar Ituño'],
    director: 'Álex Pina',
    palette: ['#3a0808', '#c41e3a', '#f0d040'],
    accent: '#c41e3a',
    kind: 'series',
  },
  {
    id: 'bear',
    title: 'The Bear',
    enTitle: 'The Bear',
    year: 2022,
    runtime: '3 temporadas',
    genres: ['Drama', 'Comedia'],
    rating: '+15',
    synopsis: 'Un joven chef del fine dining vuelve a Chicago para dirigir el restaurante de sándwiches de su difunto hermano.',
    cast: ['Jeremy Allen White', 'Ebon Moss-Bachrach', 'Ayo Edebiri'],
    director: 'Christopher Storer',
    palette: ['#0d1f1a', '#2e5d4f', '#e8d4a0'],
    accent: '#3a8a6a',
    kind: 'series',
  },
  {
    id: 'succession',
    title: 'Succession',
    enTitle: 'Succession',
    year: 2018,
    runtime: '4 temporadas',
    genres: ['Drama', 'Comedia negra'],
    rating: '+15',
    synopsis: 'La familia Roy es conocida por su control de los mayores medios de comunicación del mundo. Cuando su patriarca se acerca a la jubilación, sus hijos disputan la sucesión.',
    cast: ['Brian Cox', 'Jeremy Strong', 'Sarah Snook', 'Kieran Culkin'],
    director: 'Jesse Armstrong',
    palette: ['#10141a', '#2a3a4a', '#7a8aa0'],
    accent: '#7a8aa0',
    kind: 'series',
  },
  {
    id: 'encanto',
    title: 'Encanto',
    enTitle: 'Encanto',
    year: 2021,
    runtime: '1h 42m',
    genres: ['Animación', 'Familiar', 'Musical'],
    rating: 'TP',
    synopsis: 'Una joven colombiana tiene que lidiar con la frustración de ser la única miembro de su familia sin poderes mágicos.',
    cast: ['Stephanie Beatriz', 'María Cecilia Botero'],
    director: 'Byron Howard, Jared Bush',
    palette: ['#2a1a3a', '#7a3a8a', '#f0a040'],
    accent: '#f0a040',
    kind: 'movie',
  },
  {
    id: 'narcos',
    title: 'Narcos',
    enTitle: 'Narcos',
    year: 2015,
    runtime: '3 temporadas',
    genres: ['Drama', 'Crimen', 'Histórica'],
    rating: '+18',
    synopsis: 'La verdadera historia del ascenso del cartel de cocaína colombiano y los esfuerzos de las autoridades para detenerlo.',
    cast: ['Pedro Pascal', 'Wagner Moura', 'Boyd Holbrook'],
    director: 'Chris Brancato',
    palette: ['#1a2a1a', '#4a6a3a', '#d4a040'],
    accent: '#d4a040',
    kind: 'series',
  },
];

const RECOMMENDATIONS = [
  {
    id: 'r1',
    movieId: 'kings-speech',
    friendId: 'sof',
    rating: 5,
    tag: 'La mejor del año',
    date: 'agosto 2026',
    text: 'Es una película que no veía hace mucho tiempo y claramente es de las mejores que he visto en mi vida por ahora. La actuación de Colin Firth es absolutamente magistral y la historia te conecta de inmediato. Llóralo conmigo.',
    likes: 12,
  },
  {
    id: 'r2',
    movieId: 'past-lives',
    friendId: 'ana',
    rating: 5,
    tag: 'Te va a romper',
    date: 'octubre 2026',
    text: 'No tenía expectativas y salí del cine sin poder hablar. Es sobre el “qué hubiera pasado si” y nunca había visto algo tan bien ejecutado. Vela con alguien que conozcas hace años.',
    likes: 24,
  },
  {
    id: 'r3',
    movieId: 'parasite',
    friendId: 'mat',
    rating: 5,
    tag: 'Imperdible',
    date: 'septiembre 2026',
    text: 'Bong Joon-ho es un genio. Cada plano es intencional, cada escena tiene capas. La segunda vez la vi y descubrí cosas que se me habían pasado. Obra maestra.',
    likes: 18,
  },
  {
    id: 'r4',
    movieId: 'bear',
    friendId: 'jul',
    rating: 4,
    tag: 'Adictiva',
    date: 'julio 2026',
    text: 'El estrés del primer episodio te va a dejar sin aire. Pero engancha como pocas series. La temporada 2 sube todavía más el nivel.',
    likes: 9,
  },
  {
    id: 'r5',
    movieId: 'spirited',
    friendId: 'val',
    rating: 5,
    tag: 'Para verla en familia',
    date: 'junio 2026',
    text: 'La vi con mi sobrina y los dos quedamos hipnotizados. Miyazaki construye un mundo que se siente real aunque sea imposible. Animación pura.',
    likes: 15,
  },
  {
    id: 'r6',
    movieId: 'oppenheimer',
    friendId: 'dan',
    rating: 4,
    tag: 'Vela en cine grande',
    date: 'agosto 2026',
    text: 'Tres horas que se sienten como una. El sonido y la fotografía son brutales. Si te gustó Interstellar, esta también te va a marcar.',
    likes: 7,
  },
  {
    id: 'r7',
    movieId: 'amelie',
    friendId: 'isa',
    rating: 5,
    tag: 'Mi favorita de siempre',
    date: 'mayo 2026',
    text: 'Cada vez que la veo me dan ganas de viajar a París y hacer cosas pequeñas por la gente que amo. Es ternura en estado puro, mi vida.',
    likes: 22,
  },
  {
    id: 'r8',
    movieId: 'roma',
    friendId: 'cam',
    rating: 4,
    tag: 'Para sentarse a contemplar',
    date: 'febrero 2026',
    text: 'No es una peli para ver con el celular en la mano. Si te entregas, te marca. Cada plano es una fotografía.',
    likes: 11,
  },
  {
    id: 'r9',
    movieId: 'kings-speech',
    friendId: 'mat',
    rating: 4,
    tag: 'Gran actuación',
    date: 'septiembre 2026',
    text: 'Coincido con Sofi. Geoffrey Rush también está a otro nivel. La química entre los dos protagonistas hace toda la película.',
    likes: 5,
  },
  {
    id: 'r10',
    movieId: 'casa-papel',
    friendId: 'nic',
    rating: 4,
    tag: 'Para maratonear',
    date: 'abril 2026',
    text: 'La primera y segunda parte son adictivas. Después decae un poco pero igual la terminé en una semana.',
    likes: 6,
  },
];

const LISTS = [
  {
    id: 'l1',
    name: 'Cine en familia',
    description: 'Lo que vemos los domingos cuando estamos todos juntos',
    visibility: 'private', // 'private' | 'friends' | 'public'
    members: ['sof', 'isa', 'dan', 'cam'],
    movieIds: ['spirited', 'encanto', 'amelie'],
    recIds: ['r5', 'r7'],
    color: '#e85d2a',
  },
  {
    id: 'l2',
    name: 'Universidad — los del 2018',
    description: 'Pelis y series que nos recomendamos del grupo de la U',
    visibility: 'friends',
    members: ['mat', 'jul', 'val', 'nic'],
    movieIds: ['parasite', 'bear', 'succession', 'oppenheimer'],
    recIds: ['r3', 'r4', 'r6'],
    color: '#3a8a6a',
  },
  {
    id: 'l3',
    name: 'Para llorar bonito',
    description: 'Solo entran las que te van a doler',
    visibility: 'public',
    members: ['ana', 'sof'],
    movieIds: ['past-lives', 'roma', 'kings-speech'],
    recIds: ['r2', 'r8', 'r1'],
    color: '#7a8aa0',
  },
];

const NOTIFICATIONS = [
  { id: 'n1', type: 'rec', friendId: 'sof', movieId: 'kings-speech', text: 'te recomendó', time: 'hace 2 h', unread: true },
  { id: 'n2', type: 'rec', friendId: 'ana', movieId: 'past-lives',   text: 'te recomendó', time: 'hace 5 h', unread: true },
  { id: 'n3', type: 'list', friendId: 'jul', listId: 'l2', text: 'te invitó a la lista', time: 'ayer', unread: true },
  { id: 'n4', type: 'rec', friendId: 'mat', movieId: 'parasite', text: 'te recomendó', time: 'hace 2 d', unread: false },
  { id: 'n5', type: 'list', friendId: 'cam', listId: 'l1', text: 'agregó una película a', time: 'hace 3 d', unread: false },
];

// Helpers
const movieById = (id) => MOVIES.find((m) => m.id === id);
const friendById = (id) => FRIENDS.find((f) => f.id === id);
const recsForMovie = (id) => RECOMMENDATIONS.filter((r) => r.movieId === id);
const friendsForMovie = (id) => recsForMovie(id).map((r) => friendById(r.friendId));

Object.assign(window, {
  FRIENDS, MOVIES, RECOMMENDATIONS, LISTS, NOTIFICATIONS,
  movieById, friendById, recsForMovie, friendsForMovie,
});
